name = "hollow-veil-fc"
compatibility_date = "2026-07-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "hollow-veil-db"
database_id = "7e778793-1d71-4b5b-bf94-034101c931fd"

[vars]
SITE_URL = "https://hollowveilfc.com"
FC_MEMBERS_URL = "https://na.finalfantasyxiv.com/lodestone/freecompany/9232379236109663864/member/"
