import { ChevronLeft, ChevronRight, Plus, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
type EventItem={id:string;title:string;description:string;start_at:string;end_at:string;location:string;visibility:string};
const pad=(n:number)=>String(n).padStart(2,'0');
export default function Events(){
 const [cursor,setCursor]=useState(()=>new Date()),[events,setEvents]=useState<EventItem[]>([]),[modal,setModal]=useState(false),[selected,setSelected]=useState<EventItem|null>(null);
 const load=()=>fetch(`/api/events?month=${cursor.getFullYear()}-${pad(cursor.getMonth()+1)}`).then(r=>r.json()).then(d=>setEvents(d.events||[]));
 useEffect(()=>{load().catch(()=>{})},[cursor]);
 const cells=useMemo(()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();return [...Array(first.getDay()).fill(null),...Array.from({length:days},(_,i)=>i+1)]},[cursor]);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const r=await fetch('/api/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(fd))});if(r.ok){setModal(false);load();}else alert('Sign in as a member or officer to create events.');};
 const today=new Date();
 return <section className="page"><header className="page-heading"><p className="eyebrow">Gather Beneath the Veil</p><h1>Event Calendar</h1><p>Raids, maps, celebrations, and quiet nights at the estate.</p></header>
 <div className="calendar-shell ornamental"><div className="calendar-top"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><ChevronLeft/></button><h2>{cursor.toLocaleString('default',{month:'long',year:'numeric'})}</h2><div><button onClick={()=>setCursor(new Date())}>Today</button><button className="gold-button" onClick={()=>setModal(true)}><Plus/>Create event</button><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><ChevronRight/></button></div></div>
 <div className="weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><span key={d}>{d}</span>)}</div>
 <div className="calendar-grid">{cells.map((d,i)=>{const date=d?`${cursor.getFullYear()}-${pad(cursor.getMonth()+1)}-${pad(d)}`:'';const dayEvents=events.filter(e=>e.start_at.startsWith(date));const isToday=d===today.getDate()&&cursor.getMonth()===today.getMonth()&&cursor.getFullYear()===today.getFullYear();return <div className={`day-cell ${!d?'blank':''}`} key={i}>{d&&<><span className={isToday?'today-ring':''}>{d}</span>{dayEvents.slice(0,3).map(ev=><button className="event-chip" key={ev.id} onClick={()=>setSelected(ev)}>{ev.title}</button>)}</>}</div>})}</div></div>
 {(modal||selected)&&<div className="modal-backdrop" onClick={()=>{setModal(false);setSelected(null)}}><div className="event-modal ornamental" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>{setModal(false);setSelected(null)}}><X/></button>{selected?<><p className="eyebrow">Event details</p><h2>{selected.title}</h2><p>{selected.description}</p><dl><dt>Begins</dt><dd>{new Date(selected.start_at).toLocaleString()}</dd><dt>Location</dt><dd>{selected.location||'To be revealed'}</dd></dl></>:<form onSubmit={submit}><p className="eyebrow">Create a gathering</p><h2>Call members together</h2><input required name="title" placeholder="Event title"/><textarea required name="description" placeholder="Detailed description"/><div className="form-row"><label>Starts<input required name="start_at" type="datetime-local"/></label><label>Ends<input required name="end_at" type="datetime-local"/></label></div><input name="location" placeholder="Location"/><select name="visibility" defaultValue="members"><option value="members">Members only</option><option value="public">Public</option></select><button className="gold-button" type="submit">Create event</button></form>}</div></div>}
 </section>;
}
