import { Check, ChevronLeft, ChevronRight, Edit3, Plus, Trash2, UserPlus, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
type Participant={user_id:string;status:'going'|'maybe';character_name:string;avatar?:string;rank:string};
type EventItem={id:string;title:string;description:string;start_at:string;end_at:string;location:string;visibility:string;participants:Participant[];my_status:'going'|'maybe'|null};
const pad=(n:number)=>String(n).padStart(2,'0');
const localInput=(value:string)=>{const d=new Date(value);const offset=d.getTimezoneOffset()*60000;return new Date(d.getTime()-offset).toISOString().slice(0,16)};
export default function Events(){
 const [cursor,setCursor]=useState(()=>new Date()),[events,setEvents]=useState<EventItem[]>([]),[modal,setModal]=useState(false),[selected,setSelected]=useState<EventItem|null>(null),[deleting,setDeleting]=useState(false),[editing,setEditing]=useState(false),[canManage,setCanManage]=useState(false),[authenticated,setAuthenticated]=useState(false),[busy,setBusy]=useState(false),[memberName,setMemberName]=useState('');
 const load=()=>fetch(`/api/events?month=${cursor.getFullYear()}-${pad(cursor.getMonth()+1)}`).then(r=>r.json()).then(d=>{setEvents(d.events||[]);setCanManage(!!d.canManage);setAuthenticated(!!d.authenticated);if(selected){const fresh=(d.events||[]).find((e:EventItem)=>e.id===selected.id);if(fresh)setSelected(fresh);}});
 useEffect(()=>{load().catch(()=>{})},[cursor]);
 const cells=useMemo(()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();return [...Array(first.getDay()).fill(null),...Array.from({length:days},(_,i)=>i+1)]},[cursor]);
 const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/events',{method:editing?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(editing&&selected?{...body,id:selected.id}:body)});const d=await r.json().catch(()=>({}));if(r.ok){setModal(false);setEditing(false);setSelected(null);load();}else alert(d.error||'The event could not be saved.');};
 const removeSelected=async()=>{if(!selected||deleting)return;if(!window.confirm(`Delete “${selected.title}”? This cannot be undone.`))return;setDeleting(true);try{const r=await fetch(`/api/events?id=${encodeURIComponent(selected.id)}`,{method:'DELETE'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'The event could not be deleted.');setEvents(current=>current.filter(event=>event.id!==selected.id));setSelected(null);}catch(error){alert(error instanceof Error?error.message:'The event could not be deleted.');}finally{setDeleting(false);}};
 const attendance=async(action:'signup'|'withdraw'|'set_participant',extra:Record<string,unknown>={})=>{if(!selected||busy)return;setBusy(true);try{const r=await fetch('/api/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,event_id:selected.id,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'The attendance list could not be updated.');await load();}catch(e){alert(e instanceof Error?e.message:'The attendance list could not be updated.');}finally{setBusy(false);}};
 const today=new Date();
 return <section className="page"><header className="page-heading"><p className="eyebrow">Gather Beneath the Veil</p><h1>Event Calendar</h1><p>Every signed-in member may join a gathering. Warden, Veilkeeper, and Watcher may create, edit, and manage them.</p></header>
 <div className="calendar-shell ornamental"><div className="calendar-top"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><ChevronLeft/></button><h2>{cursor.toLocaleString('default',{month:'long',year:'numeric'})}</h2><div><button onClick={()=>setCursor(new Date())}>Today</button>{canManage&&<button className="gold-button" onClick={()=>{setSelected(null);setEditing(false);setModal(true)}}><Plus/>Create event</button>}<button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><ChevronRight/></button></div></div>
 <div className="weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><span key={d}>{d}</span>)}</div>
 <div className="calendar-grid">{cells.map((d,i)=>{const date=d?`${cursor.getFullYear()}-${pad(cursor.getMonth()+1)}-${pad(d)}`:'';const dayEvents=events.filter(e=>e.start_at.startsWith(date));const isToday=d===today.getDate()&&cursor.getMonth()===today.getMonth()&&cursor.getFullYear()===today.getFullYear();return <div className={`day-cell ${!d?'blank':''}`} key={i}>{d&&<><span className={isToday?'today-ring':''}>{d}</span>{dayEvents.slice(0,3).map(ev=><button className="event-chip" key={ev.id} onClick={()=>{setSelected(ev);setEditing(false)}}>{ev.title}<small>{ev.participants?.length||0}</small></button>)}</>}</div>})}</div></div>
 {(modal||selected)&&<div className="modal-backdrop" onClick={()=>{setModal(false);setSelected(null);setEditing(false)}}><div className="event-modal ornamental" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>{setModal(false);setSelected(null);setEditing(false)}}><X/></button>{selected&&!editing?<><p className="eyebrow">Event details</p><h2>{selected.title}</h2><p>{selected.description}</p><dl><dt>Begins</dt><dd>{new Date(selected.start_at).toLocaleString()}</dd><dt>Ends</dt><dd>{new Date(selected.end_at).toLocaleString()}</dd><dt>Location</dt><dd>{selected.location||'To be revealed'}</dd></dl>
 <section className="attendance-panel"><div className="attendance-head"><h3>Veilbound Participants</h3><span>{selected.participants.length} signed up</span></div>{authenticated?<div className="signup-actions"><button className={selected.my_status==='going'?'active':''} onClick={()=>attendance('signup',{status:'going'})}><Check/>Going</button><button className={selected.my_status==='maybe'?'active':''} onClick={()=>attendance('signup',{status:'maybe'})}>Maybe</button>{selected.my_status&&<button onClick={()=>attendance('withdraw')}>Withdraw</button>}</div>:<p>Sign in to join this event.</p>}
 <div className="participant-list">{selected.participants.length?selected.participants.map(person=><div className="participant-row" key={person.user_id}><div><strong>{person.character_name}</strong><small>{person.rank} · {person.status}</small></div>{canManage&&<div className="participant-controls"><button onClick={()=>attendance('set_participant',{user_id:person.user_id,status:'going'})}>Going</button><button onClick={()=>attendance('set_participant',{user_id:person.user_id,status:'maybe'})}>Maybe</button><button onClick={()=>attendance('set_participant',{user_id:person.user_id,status:'remove'})}><X size={14}/></button></div>}</div>):<p className="empty-participants">No one has answered the call yet.</p>}</div>
 {canManage&&<form className="add-participant" onSubmit={e=>{e.preventDefault();attendance('set_participant',{character_name:memberName,status:'going'}).then(()=>setMemberName(''))}}><input value={memberName} onChange={e=>setMemberName(e.target.value)} placeholder="Exact character name"/><button type="submit"><UserPlus/>Add member</button></form>}</section>
 {canManage&&<div className="event-actions"><button type="button" onClick={()=>setEditing(true)}><Edit3/>Edit event</button><button className="danger-button" type="button" onClick={removeSelected} disabled={deleting}><Trash2 size={17}/>{deleting?'Deleting…':'Delete event'}</button></div>}</>:<form onSubmit={save}><p className="eyebrow">{editing?'Edit the gathering':'Create a gathering'}</p><h2>{editing?'Change the call':'Call members together'}</h2><input required name="title" placeholder="Event title" defaultValue={editing?selected?.title:''}/><textarea required name="description" placeholder="Detailed description" defaultValue={editing?selected?.description:''}/><div className="form-row"><label>Starts<input required name="start_at" type="datetime-local" defaultValue={editing&&selected?localInput(selected.start_at):''}/></label><label>Ends<input required name="end_at" type="datetime-local" defaultValue={editing&&selected?localInput(selected.end_at):''}/></label></div><input name="location" placeholder="Location" defaultValue={editing?selected?.location:''}/><select name="visibility" defaultValue={editing?selected?.visibility:'members'}><option value="members">Members only</option><option value="public">Public</option></select><button className="gold-button" type="submit">{editing?'Save changes':'Create event'}</button></form>}</div></div>}
 </section>;
}
