import { ArrowBigDown, ArrowBigUp, ChevronLeft, Flame, MessageCircle, Plus, Search, Send, Sparkles, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Post={id:string;title:string;body:string;category:string;created_by:string;created_at:number;author_name:string;author_avatar:string|null;author_rank:string;score:number;comment_count:number;user_vote:number};
type Comment={id:string;post_id:string;parent_id:string|null;body:string;created_by:string;created_at:number;author_name:string;author_avatar:string|null;author_rank:string;score:number;user_vote:number};
type Feed={posts:Post[];authenticated:boolean;canModerate:boolean;categories:string[];error?:string};
const relative=(ts:number)=>{const s=Math.max(1,Math.floor((Date.now()-ts)/1000));if(s<60)return `${s}s ago`;if(s<3600)return `${Math.floor(s/60)}m ago`;if(s<86400)return `${Math.floor(s/3600)}h ago`;if(s<604800)return `${Math.floor(s/86400)}d ago`;return new Date(ts).toLocaleDateString();};
const excerpt=(text:string)=>text.length>360?`${text.slice(0,360).trim()}…`:text;

export default function Forum(){
 const [posts,setPosts]=useState<Post[]>([]),[authenticated,setAuthenticated]=useState(false),[canModerate,setCanModerate]=useState(false),[categories,setCategories]=useState<string[]>([]),[sort,setSort]=useState('hot'),[category,setCategory]=useState('All'),[query,setQuery]=useState(''),[composer,setComposer]=useState(false),[active,setActive]=useState<Post|null>(null),[comments,setComments]=useState<Comment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async(silent=false)=>{if(!silent)setLoading(true);setError('');try{const p=new URLSearchParams({sort,category,q:query});const r=await fetch(`/api/forum?${p}`,{cache:'no-store'});const d=await r.json() as Feed;if(!r.ok)throw new Error(d.error||'Forum unavailable.');setPosts(d.posts||[]);setAuthenticated(d.authenticated);setCanModerate(Boolean(d.canModerate));setCategories(d.categories||[]);}catch(e){setError(e instanceof Error?e.message:'Forum unavailable.')}finally{if(!silent)setLoading(false)}};
 useEffect(()=>{const t=setTimeout(()=>load(false),query?250:0);return()=>clearTimeout(t)},[sort,category,query]);
 const openPost=async(post:Post,silent=false)=>{if(!silent){setActive(post);setComments([])}const r=await fetch(`/api/forum?post=${encodeURIComponent(post.id)}`,{cache:'no-store'});const d=await r.json();if(r.ok){setActive(d.post);setComments(d.comments||[]);setAuthenticated(d.authenticated);setCanModerate(Boolean(d.canModerate))}};
 useEffect(()=>{const refresh=()=>{if(document.visibilityState!=='visible')return;if(active)openPost(active,true);else load(true)};const id=window.setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);return()=>{window.clearInterval(id);document.removeEventListener('visibilitychange',refresh)}},[active,sort,category,query]);
 const vote=async(type:'post'|'comment',item:Post|Comment,value:number)=>{if(!authenticated){location.href='/login';return;}const next=item.user_vote===value?0:value;await fetch('/api/forum',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'vote',target_type:type,target_id:item.id,value:next})});const delta=next-item.user_vote;if(type==='post'){setPosts(v=>v.map(p=>p.id===item.id?{...p,user_vote:next,score:p.score+delta}:p));setActive(p=>p&&p.id===item.id?{...p,user_vote:next,score:p.score+delta}:p)}else setComments(v=>v.map(c=>c.id===item.id?{...c,user_vote:next,score:c.score+delta}:c));};
 const createPost=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const r=await fetch('/api/forum',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'create_post',...Object.fromEntries(fd)})});const d=await r.json();if(!r.ok){alert(d.error||'Could not publish.');return;}setComposer(false);await load();const created=(await fetch(`/api/forum?post=${d.id}`).then(x=>x.json())).post;if(created)openPost(created)};
 const reply=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!active)return;const form=e.currentTarget,fd=new FormData(form);const r=await fetch('/api/forum',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'create_comment',post_id:active.id,body:fd.get('body')})});const d=await r.json();if(!r.ok){alert(d.error||'Reply failed.');return;}form.reset();openPost(active)};
 const remove=async(type:'post'|'comment',id:string)=>{if(!confirm(`Delete this ${type}? This cannot be undone.`))return;const r=await fetch(`/api/forum?type=${type}&id=${encodeURIComponent(id)}`,{method:'DELETE'});const d=await r.json();if(!r.ok){alert(d.error||'Delete failed.');return;}if(type==='post'){setActive(null);load()}else if(active)openPost(active)};
 const grouped=useMemo(()=>comments.reduce<Record<string,Comment[]>>((a,c)=>{(a[c.parent_id||'root']??=[]).push(c);return a},{}),[comments]);
 const renderComments=(parent='root',depth=0):React.ReactNode=>(grouped[parent]||[]).map(c=><div className="forum-comment" style={{'--depth':Math.min(depth,5)} as React.CSSProperties} key={c.id}><Vote score={c.score} vote={c.user_vote} onVote={v=>vote('comment',c,v)}/><div className="forum-comment-body"><Author item={c}/><p>{c.body}</p>{canModerate&&<button className="forum-delete-mini" onClick={()=>remove('comment',c.id)}><Trash2 size={13}/> Delete</button>}{renderComments(c.id,depth+1)}</div></div>);
 return <section className="page forum-page"><header className="page-heading forum-heading"><div><p className="eyebrow">Voices Beneath the Boughs</p><h1>The Hollow Board</h1><p>Stories, strategies, questions, discoveries, and conversations remembered by the forest.</p></div><button className="gold-button" onClick={()=>authenticated?setComposer(true):location.assign('/login')}><Plus/>Create post</button></header>
 <div className="forum-toolbar ornamental"><div className="forum-sort"><button className={sort==='hot'?'active':''} onClick={()=>setSort('hot')}><Flame/>Hot</button><button className={sort==='new'?'active':''} onClick={()=>setSort('new')}><Sparkles/>New</button><button className={sort==='top'?'active':''} onClick={()=>setSort('top')}><ArrowBigUp/>Top</button></div><label className="forum-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the Hollow Board"/></label></div>
 <div className="forum-layout"><aside className="forum-categories ornamental"><h3>Gathering Places</h3>{['All',...categories].map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}><span>{c}</span><small>{c==='All'?posts.length:posts.filter(p=>p.category===c).length}</small></button>)}</aside>
 <div className="forum-feed">{error&&<div className="forum-empty">{error}</div>}{loading?<div className="forum-empty">Listening for voices in the Veil…</div>:posts.length===0?<div className="forum-empty"><h2>No voices answered.</h2><p>Be the first to begin a thread here.</p></div>:posts.map(post=><article className="forum-post ornamental" key={post.id}><Vote score={post.score} vote={post.user_vote} onVote={v=>vote('post',post,v)}/><div className="forum-post-main" onClick={()=>openPost(post)}><div className="forum-post-meta"><span className="forum-category">{post.category}</span><Author item={post}/></div><h2>{post.title}</h2><p>{excerpt(post.body)}</p><div className="forum-post-footer"><span><MessageCircle/> {post.comment_count} {post.comment_count===1?'reply':'replies'}</span><span>{relative(post.created_at)}</span></div></div></article>)}</div></div>
 {composer&&<div className="modal-backdrop"><form className="modal forum-composer ornamental" onSubmit={createPost}><button type="button" className="close" onClick={()=>setComposer(false)}><X/></button><p className="eyebrow">Speak Into the Veil</p><h2>Create a new post</h2><label>Title<input name="title" maxLength={180} required placeholder="What do you wish to ask or share?"/></label><label>Gathering place<select name="category">{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Message<textarea name="body" maxLength={10000} required rows={10} placeholder="Write with purpose. The forest remembers every word."/></label><button className="gold-button" type="submit"><Send/>Publish post</button></form></div>}
 {active&&<div className="forum-thread-overlay"><article className="forum-thread"><header><button onClick={()=>setActive(null)}><ChevronLeft/>Back to the board</button><button onClick={()=>setActive(null)} aria-label="Close"><X/></button></header><div className="forum-thread-post ornamental"><Vote score={active.score} vote={active.user_vote} onVote={v=>vote('post',active,v)}/><div><span className="forum-category">{active.category}</span><h1>{active.title}</h1><Author item={active}/><p className="forum-thread-copy">{active.body}</p>{canModerate&&<button className="forum-delete-mini" onClick={()=>remove('post',active.id)}><Trash2 size={14}/> Delete post</button>}</div></div><section className="forum-replies"><h2>{comments.length} {comments.length===1?'Reply':'Replies'}</h2>{authenticated?<form className="forum-reply-box" onSubmit={reply}><textarea name="body" rows={4} required maxLength={5000} placeholder="Add your voice to this discussion…"/><button className="gold-button"><Send/>Reply</button></form>:<button className="forum-signin-call" onClick={()=>location.assign('/login')}>Sign in to join the discussion</button>}<div className="forum-comments">{renderComments()}</div></section></article></div>}
 </section>;
}
function Vote({score,vote,onVote}:{score:number;vote:number;onVote:(value:number)=>void}){return <div className="forum-vote"><button className={vote===1?'active':''} onClick={()=>onVote(1)} aria-label="Upvote"><ArrowBigUp/></button><strong>{score}</strong><button className={vote===-1?'active down':''} onClick={()=>onVote(-1)} aria-label="Downvote"><ArrowBigDown/></button></div>}
function Author({item}:{item:{author_name:string;author_avatar:string|null;author_rank:string;created_at:number}}){return <span className="forum-author">{item.author_avatar?<img src={item.author_avatar} alt=""/>:<span className="forum-avatar-fallback"/>}<b>{item.author_name}</b><em>{item.author_rank}</em><small>· {relative(item.created_at)}</small></span>}
