const JOB_ICON_BY_NAME: Record<string, string> = {
  'Alchemist': '/job-icons/alchemist.png',
  'Arcanist': '/job-icons/arcanist.png',
  'Archer': '/job-icons/archer.png',
  'Armorer': '/job-icons/armorer.png',
  'Astrologian': '/job-icons/astrologian.png',
  'Bard': '/job-icons/bard.png',
  'Black Mage': '/job-icons/black-mage.png',
  'Blacksmith': '/job-icons/blacksmith.png',
  'Blue Mage': '/job-icons/blue-mage.png',
  'Botanist': '/job-icons/botanist.png',
  'Carpenter': '/job-icons/carpenter.png',
  'Conjurer': '/job-icons/conjurer.png',
  'Culinarian': '/job-icons/culinarian.png',
  'Dancer': '/job-icons/dancer.png',
  'Dark Knight': '/job-icons/dark-knight.png',
  'Dragoon': '/job-icons/dragoon.png',
  'Fisher': '/job-icons/fisher.png',
  'Gladiator': '/job-icons/gladiator.png',
  'Goldsmith': '/job-icons/goldsmith.png',
  'Gunbreaker': '/job-icons/gunbreaker.png',
  'Lancer': '/job-icons/lancer.png',
  'Leatherworker': '/job-icons/leatherworker.png',
  'Machinist': '/job-icons/machinist.png',
  'Marauder': '/job-icons/marauder.png',
  'Miner': '/job-icons/miner.png',
  'Monk': '/job-icons/monk.png',
  'Ninja': '/job-icons/ninja.png',
  'Paladin': '/job-icons/paladin.png',
  'Pictomancer': '/job-icons/pictomancer.png',
  'Pugilist': '/job-icons/pugilist.png',
  'Reaper': '/job-icons/reaper.png',
  'Red Mage': '/job-icons/red-mage.png',
  'Rogue': '/job-icons/rogue.png',
  'Sage': '/job-icons/sage.png',
  'Samurai': '/job-icons/samurai.png',
  'Scholar': '/job-icons/scholar.png',
  'Summoner': '/job-icons/summoner.png',
  'Thaumaturge': '/job-icons/thaumaturge.png',
  'Viper': '/job-icons/viper.png',
  'Warrior': '/job-icons/warrior.png',
  'Weaver': '/job-icons/weaver.png',
  'White Mage': '/job-icons/white-mage.png',
};

export function localJobIcon(job?: string) {
  return job ? JOB_ICON_BY_NAME[job] : undefined;
}
